version: '3'

services:
  web:
    build: .
    volumes:
      - ./app:/app/app
      - ./config:/app/config
      - ./certs:/app/certs
      - ./wsdl:/app/wsdl  # Mount WSDL files from host to container
    env_file:
      - .env.test
    environment:
      - PYTHONUNBUFFERED=1
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME:-comcorp_idx_user}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD:-MGBNU4DyJnSXaUT}
    expose:
      - 8000
    restart: always
    networks:
      - app-network
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: comcorp-idx-connector-test

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx_docker.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
    networks:
      - app-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge